steps:
 - name : 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
          gcloud compute ssh dev-linuxvm 
		  --zone=us-central1-c 
		  --command "
          timestamp=\$(date +\"%Y%m%d%H%M%S\");
		  mkdir -p /var/www/dpma_backups;
          if [ -d /var/www/my_app ]; then
            mv /var/www/my_app /var/www/backups/my_app_\$timestamp;
		    echo 'Backup moved;'
		  else
		    echo 'Backup Failed';"
			
options:
  logging: CLOUD_LOGGING_ONLY
