steps:
  # Step 1: Backup existing code by moving
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud compute ssh dev-linuxvm --zone=us-central1-c --command "
          timestamp=\$(TZ="Asia/Kolkata" date +"%Y%m%d%H%M%S");
          if [ -d /var/www/my_app ]; then
            mv /var/www/my_app /var/www/backups/my_app_\$timestamp;
            echo 'Backup moved';
          else
            echo '⚠️ No existing';
          fi
          mkdir -p /var/www/my_app
        "

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud compute scp --recurse /workspace/* dev-linuxvm:/var/www/my_app --zone=us-central1-c
        # gcloud compute ssh dev-linuxvm --zone=us-central1-c --command 'cd /var/www/my_app && npm install && npm run build'
options:
  logging: CLOUD_LOGGING_ONLY
